import psycopg
import sys
import tomllib

from psycopg import sql

env = sys.argv[1]

with open(f"{env}.toml", "rb") as f:
    config = tomllib.load(f)

    DBNAME = config['database']['name']
    USER = config['database']['user']

con = psycopg.connect(user=USER, host='localhost')
con.autocommit = True

cur = con.cursor()

try:
    db_drop_query = f"DROP DATABASE {DBNAME}"
    cur.execute(sql.SQL(db_drop_query))
except psycopg.errors.InvalidCatalogName:
    pass

db_create_query = f"CREATE DATABASE {DBNAME}"
cur.execute(sql.SQL(db_create_query))

with psycopg.connect(f"dbname={DBNAME} user={USER}") as conn:

    with conn.cursor() as cur:

        cur.execute("""
            CREATE TABLE product (
                id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                title VARCHAR(30) NOT NULL,
                category VARCHAR(15) NOT NULL,
                kondisi VARCHAR(15) NOT NULL,
                qty INTEGER NOT NULL,
                price INTEGER NOT NULL
            )
        """)

        conn.commit()
